name: Terraform Module
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    TERRAFORM_MODULE:
      # Terraform module workflow reference
      uses: CiscoOpsStack/ops_stack_github_actions/.github/workflows/terraform_module.yml@main
      secrets: 
        GH_PAT_TOKEN: "${{ secrets.GH_PAT_READ_TOKEN }}"
      with:
        TF_VERSION: 1.5.0