name: Terraform Module
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    TERRAFORM_MODULE:
      # Terraform module workflow reference
      uses: CiscoOpsStack/ops_stack_github_actions/.github/workflows/terraform_module.yml@main
      secrets: 
        GH_Token: "${{ secrets.GITHUB_TOKEN }}"
        ci_deploy_token: "${{ secrets.GITHUB_TOKEN }}"
      with:
        TF_VERSION: 1.3.1
